TRAINLINES = ["armadale", "fremantle", "joondalup",
              "mandurah", "midland", "thornlie"]

STATIONS = {
    "armadale": [
        "armadale",
        "sherwood",
        "challis",
        "kelmscott",
        "seaforth",
        "gosnells",
        "maddington",
        "kenwick",
        "beckenham",
        "cannington",
        "queens park",
        "welshpool",
        "oats street",
        "carlisle",
        "victoria park",
        "burswood",
        "perth stadium",
        "claisebrook",
        "mciver"
    ],
    "fremantle": [
        "fremantle",
        "north fremantle",
        "victoria street",
        "mosman park",
        "cottesloe",
        "grant street",
        "swanbourne",
        "claremont",
        "showgrounds",
        "loch street",
        "karrakatta",
        "shenton park",
        "daglish",
        "subiaco",
        "west leederville",
        "city west"
    ],
    "joondalup": [
        "butler",
        "clarkson",
        "currambine",
        "joondalup",
        "edgewater",
        "whitfords",
        "greenwood",
        "warwick",
        "stirling",
        "glendalough",
        "leederville",
        "perth underground"
    ],
    "mandurah": [
        "mandurah",
        "warnbro",
        "rockingham",
        "wellard",
        "kwinana",
        "aubin grove",
        "cockburn central",
        "murdoch",
        "bull creek",
        "canning bridge",
        "elizabeth quay",
        "perth underground"
    ],
    "midland": [
        "midland",
        "woodbridge",
        "east guildford",
        "guildford",
        "success hill",
        "bassendean",
        "ashfield",
        "bayswater",
        "meltham",
        "maylands",
        "mt lawley",
        "east perth",
        "claisebrook",
        "mciver"
    ],
    "thornlie": [
        "thornlie",
        "beckenham",
        "cannington",
        "queens park",
        "welshpool",
        "oats street",
        "carlisle",
        "victoria park",
        "burswood",
        "perth stadium",
        "claisebrook",
        "mciver"
    ]
}

DIRECTIONS = ["to perth", "from perth"]
